version: '2.1'

volumes:
  tailscale-state:

services:
  tailscale:
    image: tailscale/tailscale:latest
    container_name: tailscale
    network_mode: 'host'
    privileged: true
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - tailscale-state:/var/lib/tailscale
    environment:
      - TS_AUTHKEY # Set in Balena variables
      - TS_ROUTES # Set in Balena variables
      - TS_ACCEPT_ROUTES # Set in Balena variables
      - TS_HOSTNAME # Set in Balena variables
    restart: unless-stopped
  intermediate-server:
    build: ./node-server
    ports:
      - '80:80'
    environment:
      - PORT=80
      - APP_URL=http://localhost:3000
      - NODE_ENV=staging
      - RUN_TESTS=false
      - LOG_LEVEL=debug
  iperf3:
    image: taoyou/iperf3-alpine
    container_name: iperf3-server
    command: ['-s', '-p', '5201', '--bind', '0.0.0.0']
    network_mode: 'host'
    depends_on:
      - tailscale
    restart: unless-stopped
